Added singularity to getNetlink and getFRR status information
telekom/das-schiff-network-operator pull request #114
Opened 2024-04-22 11:33 UTC by Cellebyte

* Concurrent requests for frr and netlink should only do a single backend call instead of multiple calls

2024-04-22 14:50 UTC, schrej requested changes

2024-04-22 14:50 UTC, schrej commented on pkg/monitoring/collector.go
> +			defer wg.Done()
For defer to be useful here this should be executed before calling that execute function.

2024-04-22 14:50 UTC, schrej commented on pkg/monitoring/nl.go
> +	defer c.mu.Unlock()
locking shouldn't be required here

2024-04-22 14:50 UTC, schrej commented on pkg/monitoring/nl.go
> +	defer c.mu.Unlock()
locking shouldn't be required here

2024-04-22 16:01 UTC, Cellebyte commented on pkg/monitoring/collector.go
> +			defer wg.Done()
fixed

2024-04-22 16:02 UTC, Cellebyte commented on pkg/monitoring/nl.go
> +	defer c.mu.Unlock()
fixed

2024-04-23 16:03 UTC, schrej approved these changes

2024-04-23 17:02 UTC, merged