Added preferred maximum-path configuration from broadcom
telekom/das-schiff-network-operator pull request #6
Opened 2023-05-30 10:54 UTC by Cellebyte

* Add suggestions from broadcom via Environment Variable.
* hotfix.

2023-05-30 13:34 UTC, schrej requested changes
One bug, lgtm otherwise

2023-05-30 13:34 UTC, schrej commented on pkg/frr/configure.go
> +	envECMPMaximumPaths, isSet := os.LookupEnv("NWOP_ECMP_MAXIMUM_PATHS")
FYI: The second return value is commonly called `ok` for things like this, but no need to change that.

2023-05-30 13:34 UTC, schrej commented on pkg/frr/configure.go
> +	}
I would implement it like this, which is a more common style and reduces scope of some of the variables.

In addition the if condition for error handling was the wrong way round, which is corrected here as well.

```suggestion
	ecmpMaximumPaths := 8 // Default to BCMs preferred target of maximum 8 paths per route.
	if envECMPMaximumPaths, ok := os.LookupEnv("NWOP_ECMP_MAXIMUM_PATHS"); ok {
		parsedECMPMaximumPaths, err := strconv.Atoi(envECMPMaximumPaths)
		if err != nil {
			return nil, err
		}
		ecmpMaximumPaths = parsedECMPMaximumPaths
	}
```

2023-05-31 07:27 UTC, schrej approved these changes
go part lgtm

2023-06-30 10:35 UTC, Cellebyte commented
should we still add this feature as a global configuration or not?

2023-08-28 11:11 UTC, MaxRink commented
@Cellebyte we should default to something sane

2023-09-27 16:02 UTC, Cellebyte commented
> @Cellebyte we should default to something sane

What is something sane @MaxRink ?

2024-04-23 17:03 UTC, Cellebyte commented
Closed as not needed

2024-04-23 17:03 UTC, closed without merging